dist: trusty
sudo: required
script: "bundle exec rake travis"
before_script: ./bin/ci/before_build.sh
after_failure: ./bin/ci/after_failure.sh
services: mongodb
rvm:
  - 2.5.0
notifications:
  email:
    - didier@nocoffee.fr
  irc: "irc.freenode.org#locomotivecms"
branches:
  only:
    - master
    - debug-travis-ci
addons:
  chrome: stable
  hosts:
    - locomotive.local

